Issue/9
DaichiNiwa/lamp_practice pull request #10
Opened 2019-10-12 07:53 UTC by DaichiNiwa

CSRF対策を以下のように実装しました。

①function.phpにトークン生成関数（get_csrf_token)とトークンチェック関数（is_valid_csrf_token）を追記する。

②以下の送信側ファイルにトークン生成関数を追記する。
lamp_practice\www\html\admin.php
lamp_practice\www\html\cart.php
lamp_practice\www\html\finish.php
lamp_practice\www\html\index.php
lamp_practice\www\html\login.php
lamp_practice\www\html\signup.php

③以下の送信側viewファイル内の送信フォームにトークンを埋め込む。
lamp_practice\www\view\cart_view.php
lamp_practice\www\view\admin_view.php
lamp_practice\www\view\index_view.php
lamp_practice\www\view\login_view.php
lamp_practice\www\view\signup_view.php

④以下の受信側ファイルにトークンチェック関数を追記する。
lamp_practice\www\html\admin_change_status.php
lamp_practice\www\html\admin_change_stock.php
lamp_practice\www\html\admin_delete_item.php
lamp_practice\www\html\admin_insert_item.php

lamp_practice\www\html\cart_change_amount.php
lamp_practice\www\html\cart_delete_cart.php

lamp_practice\www\html\index_add_cart.php

lamp_practice\www\html\login_process.php

lamp_practice\www\html\signup_process.php

lamp_practice\www\html\finish.php

2019-10-12 16:51 UTC, thisprodigiousgeek commented on www/html/finish.php
> +
こちらのファイルについては、この後トークンの書き換えが行われず、
この時に利用されたトークンがそのまま有効になってしまいますね！
フォームは存在しませんが、トークンの書き換えは行うようにしましょう。

2019-10-12 16:52 UTC, thisprodigiousgeek requested changes
CSRF対策についても良くご理解いただけていらっしゃいますね！素晴らしいです。
あとはテスト用のファイルの削除と、finish.phpでのトークン書き換えのみです。
最後の仕上げ、頑張っていきましょう！

2019-10-15 13:31 UTC, thisprodigiousgeek commented on www/html/finish.php
> +  get_csrf_token();
get_csrf_tokenの位置をif文の外に出すのでしたね！
修正しておきましょう！

2019-10-15 13:33 UTC, thisprodigiousgeek requested changes
finish.phpのget_csrf_tokenの位置と
前２つのブランチをマージしたことによるコンフリクトを解消すれば終了ですね！
残りわずか、最後の仕上げ頑張っていきましょう！

2019-10-16 13:08 UTC, DaichiNiwa commented
finish.phpのget_csrf_tokenの位置とコンフリクトを解消しました。
よろしくお願いします。

2019-10-18 00:58 UTC, thisprodigiousgeek approved these changes
はい、こちらでバッチリです！マージさせていただきます！

2019-10-18 00:58 UTC, merged