Issue/11
DaichiNiwa/lamp_practice pull request #12
Opened 2019-10-12 10:03 UTC by DaichiNiwa

購入履歴テーブル作成のSQLをアップしました。

2019-10-12 16:54 UTC, thisprodigiousgeek commented on lamp_dock/append_schema.sql
> +CREATE TABLE histories (
惜しいです！現状ではどのユーザーが購入した履歴なのかがわかりませんね。
また、価格については「購入時の」価格であることがわかるようなカラム名がベターです。

2019-10-12 23:51 UTC, thisprodigiousgeek reviewed
はい、まずは良い感じになってきましたね！
残るは正規化と注文番号の問題となりますがこちらについてはレッスンで扱っていきましょう。
9:00~のレッスンよろしくお願いいたします！

2019-10-15 13:36 UTC, thisprodigiousgeek requested changes
いい感じに分割できてきていますね！
あとは、purchased_cartsにも管理用に作成日時を追加しておくと良いでしょう。
また、更新日時用のカラムについても、各テーブルに追加しておくと管理上便利ですので、
ついでに追加しておきましょう！

2019-10-16 13:55 UTC, DaichiNiwa commented
SQLに作成日時と更新日時のカラムを追加しました
よろしくお願いします

2019-10-18 01:01 UTC, thisprodigiousgeek approved these changes
はい、こちらもオッケーです！マージさせていただきます！

2019-10-18 01:01 UTC, merged