#17 　課題3-2　ページネーション機能の追加
DaichiNiwa/lamp_practice pull request #18
Opened 2019-10-19 10:48 UTC by DaichiNiwa

よろしくお願いします。

2019-10-19 11:04 UTC, thisprodigiousgeek commented on www/html/index.php
> +// ゲットで現在のページ番号を取得。ないときはトップページとして１
get_get関数で値が存在しなかった場合のデフォルト値が指定できるとスマートに書けそうですね！
例えば $page = get_get('page', 1) とした時に、$_GET['page']がnullならば、1を返り値にするような関数にするには
どのような実装が必要になるでしょうか。

2019-10-19 11:07 UTC, thisprodigiousgeek commented on www/html/index.php
> +  . ($list_start_number + 8)
この8という数字はコードに直接書いてしまうと、
表示件数が変更になった時に修正が面倒そうですね！

2019-10-19 11:07 UTC, thisprodigiousgeek commented on www/model/item.php
> +      LIMIT :list_start_number, 8
ここの8も気になりますね！

2019-10-19 11:09 UTC, thisprodigiousgeek commented on www/model/item.php
> +function get_items($db, $is_open = false, $list_start_number = null){
$list_start_numberのデフォルト値がnullになっていることで不要な分岐が必要になっているようです。
分岐が不要になるようなデフォルト値はないでしょうか？

2019-10-19 11:10 UTC, thisprodigiousgeek commented on www/model/item.php
> +  return get_items($db, true, $list_start_number);
今までget_open_itemsが利用されていた箇所で全てコードの書き換えが必要になりそうです。
今までの箇所を変更せずに利用できるようにするにはどうすれば良いでしょうか。

2019-10-19 11:10 UTC, thisprodigiousgeek commented on www/view/index_view.php
> +      <?php for ($i=1; $i <= $total_pages_number; $i++){ ?>
小さなところですが、演算子の左右は必ず半角スペースを空けましょう。

2019-10-19 11:12 UTC, thisprodigiousgeek requested changes
ページネーションについても基本の実装方法はしっかり理解できていらっしゃいますね！
まずはコメントを参考に、特に関数のデフォルト値について再考してみましょう！

2019-10-20 09:42 UTC, DaichiNiwa commented
前回のレビューで指摘いただいた点を修正しました。
関数get_itemsとget_open_itemsはまで違和感がありますが、自分で考えてできるのがここまでだったので、ここでレビューをお願いします。

2019-10-21 06:57 UTC, thisprodigiousgeek requested changes
get_itemsとget_open_items、いい感じになってきましたね！
せっかくですので一回に取得する商品数についても
文字列連結ではなく名前付きプレースホルダを利用しましょう。
また、ページ数の表示について、
現状は例えば商品数が2件しかなくても1 - 8件の商品と表示されてしまいそうです。
こちらについても修正しておきましょう。

2019-10-24 12:42 UTC, DaichiNiwa commented
「xx件中 xx - xx件の商品」の表示部分について修正しました。
よろしくお願いします。

2019-10-24 13:30 UTC, thisprodigiousgeek commented on www/model/item.php
> +  } elseif($all_items_amount - $list_start_number === 1){
一つ前のreturn （こういうreturnはアーリーリターンとか、ガード節とかの呼び名があります。）によって、
上の条件に当てはまっている場合にはそこで処理が中断します。
そのためelseは不要になります。
elseはどうしても必要な時にだけ利用すると読みやすくなりますね！

2019-10-24 13:31 UTC, thisprodigiousgeek commented on www/model/item.php
> +    return "{$all_items_amount}件中 {$all_items_amount}件の商品";
細かくて恐縮ですが、正確にはn件中n件「目」の商品になりますね！

2019-10-24 13:31 UTC, thisprodigiousgeek commented on www/model/item.php
> +  } elseif($all_items_amount - $list_start_number < 8){
このelseもやはり不要になります。
また、この8はマジックナンバーになるので定数を使いましょう！

2019-10-24 13:43 UTC, thisprodigiousgeek commented on www/model/item.php
> +function make_items_count_text($all_items_amount, $list_start_number){
この $list_start_numberは
* ページ数 * 表示件数
* ページ数 * 表示件数 + 1
のどちらを表しているのかわかりにくいですね！
表示件数は定数で取得できるので、ページ数を引数にするとわかりやすくなります。

2019-10-24 13:44 UTC, thisprodigiousgeek requested changes
make_items_count_text関数を利用するところまではバッチリですね！
あとは、この関数が理解しやすいものになるよう
明日のレッスンで整理してみましょう！

2019-10-25 15:01 UTC, thisprodigiousgeek approved these changes
こちらでバッチリですね！
マージさせていただきます！

2019-10-25 15:01 UTC, merged